---
abstract: 'A fully event-driven networkable IRC server daemon module'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.44
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: POE::Component::Server::IRC
name: POE-Component-Server-IRC
no_index:
  directory:
    - xt
    - inc
    - t
requires:
  Algorithm::Diff: 1.19
  Carp: 0
  Crypt::PasswdMD5: 1.3
  Date::Format: 0
  Net::Netmask: 1.9012
  POE: 0.9999
  POE::Component::Client::DNS: 1
  POE::Component::Client::Ident: 1
  POE::Component::IRC: 5.18
  POE::Filter::IRCD: 2.2
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
  constant: 0
  perl: 5.6.0
  strict: 0
  vars: 0
tests: 't/*.t xt/*.t'
version: 1.32
