---
abstract: 'A fully event-driven networkable IRC server daemon module.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  POE::Component::IRC: 5.70
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-IRC
no_index:
  directory:
    - t
    - xt
    - examples
recommends:
  POE::Component::SSLify: 0
  POE::Filter::Zlib::Stream: 0
requires:
  Algorithm::Diff: 1.19
  Crypt::PasswdMD5: 1.3
  Date::Format: 0
  Net::Netmask: 1.9012
  Object::Pluggable: 1.29
  POE: 0.9999
  POE::Component::Client::DNS: 1.00
  POE::Component::Client::Ident: 1.00
  POE::Filter::IRCD: 2.2
  constant: 1.17
  perl: 5.006
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=POE-Component-Server-IRC
  homepage: http://search.cpan.org/dist/POE-Component-Server-IRC/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-server-irc.git
version: 1.41
x_authority: cpan:BINGOS
