---
abstract: 'A fully event-driven networkable IRC server daemon module'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-IRC
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Algorithm::Diff: 1.19
  Carp: 0
  Crypt::PasswdMD5: 1.3
  Date::Format: 0
  Net::Netmask: 1.9012
  POE: 0.9999
  POE::Component::Client::DNS: 1
  POE::Component::Client::Ident: 1
  POE::Component::IRC: 5.7
  POE::Component::Pluggable: 1.14
  POE::Filter::IRCD: 2.2
  POE::Filter::Line: 0
  POE::Filter::Stackable: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.37_01
